import modulocalc as cl  
suma = cl.sumar(2,4)
resta = cl.restar(4,1)
multiplicacion = cl.multiplicar(4,12)
division01 = cl.dividir(12,3)
division02 = cl.dividir(3,0)
print("*"*80)
print("Resultados:")
print(f"La suma es {suma}")
print(f"La resta es {resta}")
print(f"La multiplicacion es {multiplicacion}")
print(f"La division es {division01}")
print(f"La division es {division02}")
