#operadores aritmeticos
print('suma')
print(2+5)
print('resta')
print(5-3)
print('multiplicacion')
print(3*5)
print('division')
print(6/3)
print('potencia')
print(3**2)
print('modulo')
print(7%4)
print('parte entera')
print(9//4)